@server = https://effective-fishstick-qw57v4j76xxf497j-8080.app.github.dev
###
GET {{server}}/api/libros/2
###
POST {{server}}/api/libros
Content-Type: application/json

{"nombre": "Quena", "año": "Viento", "editorial": "Como una flauta"}
###
GET {{server}}/api/autores
###
POST {{server}}/api/autores
Content-Type: application/json

{"nombre": "Joaquín"}
###
GET {{server}}/api/bibliotecas
###
GET {{server}}/api/bibliotecas/1

###
GET {{server}}/api/detalles
